name: Auto Assign

on:
  issues:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      actions: read

    steps:
    - name: 'Auto-assign issue creator'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.event.issue.user.login }} # Assign the issue creator
        numOfAssignee: 1
